# This config depends on the defaults.yml testplan
# Only diverging settings are defined here
prepare_shop:
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/twig-admin-theme": "dev-b-7.1.x-add-low-stock-message-OXDEV-5103",
              "oxid-esales/apex-theme": "dev-b-7.1.x-add-low-stock-message-OXDEV-5103"
          }
      }

codeception:
  # Running on public runners, this should pose no problem
  max_parallel: &codeception_max_parallel 1

runtest:
  composer:
    transform: |
      {
          "require-dev": {
              "oxid-esales/tests-deprecated-ce": "dev-b-7.1.x",
              "oxid-esales/codeception-page-objects": "dev-b-7.1.x-add-low-stock-message-OXDEV-5103",
              "codeception/module-webdriver": "^3.1",
              "phpunit/phpunit": "^9.6"
          }
      }

phpcs_tests:
  # Check all files in the full check
  diff_only: false
  filter: '^\./source/Internal/.*\.php$'

sonarcloud:
  matrix:
    testplan: '["-","tests/github_actions/sonarcloud_oxideshop_ce_internal.yml"]'
  target_branch: b-7.1.x-add-low-stock-message-OXDEV-5103

finish:
  slack_title: 'OXDEV 7522 CE ({{ .Data.global.git.shop_ref }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
